name: Terraform fmt
on: 
  - push

jobs:
  terraform_fmt:
    name: Check Terraform format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: terraform fmt
        run: terraform fmt -recursive -check
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Actions] Format Terraform files"