name: Draw Infrastructure's Architecture to SVG
on: 
  push:
    branches:
      - main
      - stg

jobs:
  draw:
    name: Draw Infrastructure's Architecture to SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: rlespinasse/drawio-export-action@v2
        with:
          format: svg
          path: docs/architecture.drawio
          output: docs
          transparent: false  
          action-mode: recent        
      - name: 
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "GitHub Actions から差分を Push"; \
            git push origin HEAD:${GITHUB_REF}; \
          else \
            echo "No changes..."; \
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      