name: Draw Infrastructure's Architecture to SVG
on: 
  push:
    branches:
      - main
      - stg

jobs:
  draw:
    name: Draw Infrastructure's Architecture to SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Burnett01/actions-drawio@1.2
        with:
          src: docs/architecture.drawio
          dest: docs/architecture.svg
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Actions] Draw SVG file"
          ref: ${{ github.head_ref }}
      