name: Draw Infrastructure's Architecture to SVG
on: 
  push:
    branches:
      - main
      - stg
    path:
      - "./docs/architecture.drawio"
      - ".github/workflows/draw_architecture.yml"

jobs:
  draw:
    name: Draw Infrastructure's Architecture to SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: rlespinasse/drawio-export-action@v2
        with:
          format: jpg
          path: ./docs/architecture.drawio
          output: ./
          transparent: false  
          action-mode: all
      - name: Rename file
        run: mv ./docs/architecture-Page-1.svg ./docs/architecture.svg
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Draw Infrastructure's Architecture
        