name: Draw Infrastructure's Architecture to SVG
on: 
  push:
    branches:
      - main
      - stg

jobs:
  draw:
    name: Draw Infrastructure's Architecture to SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: rlespinasse/drawio-export-action@v2
        with:
          format: svg
          path: docs
          output: docs
          transparent: false          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Actions] Draw SVG file"
      